language: node_js
node_js:
  - '8'

sudo: required

before_deploy: npm run build
deploy:
  provider: releases
  api_key:
    secure: "s0V5I0ycbj77xFvrX1jnZU+Lg66afcxcVyXzmHHwR1vNKPGbRP9nRBHwK7wEvD99HiYXRcEs2w7H9fFVf+/BTpujdD5GudPjkiIbCl7BXuFZGmvYjuLO4lxtQHN3Tc2VnmEvzZeMbWNsAmT0+dnzeQNu8AVSM2wv4tIIUGFskj3PLWZoUiTBsO6LQ7YLrwZ8A+trF9TL8o55GwRDPBPNgJFRtbBYVkKunPhOQeMz+Dzz7CUFrjMkoj0Gef/QH+zuAmp9wyIqP8LvwTr1S1jKAK36gy7PpbO1bTX+fFsWusYbg9uGEAfs016J++9tqsJkAYkpCMW7POjgreDUOfx9intCLha1k32YXQaefonjYXb5Z+8QtHx3QU6ztRwg4hTvpavedaPF7NnudEQMPDRqxo58kf1sQvdvXJwcTbfjlP/j2V4cxeRllnwn1be8VlCtpkVfJ+8uiJo+UZmr4YFnB8DduYaKYoHC4BaqzN84q3WgqMCC+o+7qlt/48FvsVP+31LyAZMvwf4WhoSofw/yAH6PQjCySARnlTLQhKdR8NLMnpUNQUuSKDu2Phbvmt9/jnvbI27dMWZFodmPNjzfS0kHVWUMq8VI220Bu9U18gmt3I4okmv3+oD3Ju0fKRP4kEySfMjYdexrq4GtBuDcLdxfCJocL/uvswh/Lyt9Z8o="
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true

branches:
  except:
    - gh-pages

cache:
  directories:
    - node_modules
