language: node_js
node_js:
  - '8'

before_deploy: npm run build
deploy:
  provider: releases
  api_key:
    secure: cT2Ci2zniJoliJXtkJH3BF+MJtaDqV4MzOIRxkXEqE0aUhRVt1B/gqBw4MZb9MY3nMvlE5e2RdiCsfDf+EefBUbnnEG6DXLe4d0+au5Ylyn/qp07Z45y2B/+uuTl3Qxzw/wVjQvzIoretCZ2LOrfACRx6jOOjaxPBQKIT+kn83H122TgQgsWyVA3IL0gCXTjsgOeglI3/bMF7+qThDbg/3/hhNk8ho9m09mH5NyZxDbAXSpM059M37GlZ45vZVo/TUXYpUjI8HbwQAkF5VCDYtEdcUBlPrWz/oAgv/5rRNEaP1DVXonKr2KHY+IG815RtAqyUOyJqK6yjPr51M5AorCtatApR9R33O9mVY/uLQLhDz6Ey6Xp3w+/zuG9YXCZ8Y123517b9yccfSgPP8RhZfbS5pY6bnM3vg9xX2ZlKtpNJXZVe76mVwwmpyLm4jAHYrjoyfBl6t9n8JAkG3Y/jq1FoR7X0tWYDuVu/vseXiplX5SXvKhk+9VIugFGBKCyOETWYafTfkbmGlGAmmmJBH456o5DwntN8JK2CWpgHzIVEZyw9CnKdcGFDcL/vxw8PmWJw/43PeDQNGb/H+Hh23QNoMwE6vtf2ssFFxfPX2qSjpM9zSFiV/auLW4SQ2Rpw0rxnKQGzhYD7ev60civNFa0tCDPKLMJr0aNnRzOXg=
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true

branches:
  except:
    - gh-pages

cache:
  directories:
    - node_modules
